name = "either_or"
version = "2.0.0"

description = "A package implementing a choice type named `EitherOr` with variants `Either` and `Or`. Stemming from a failed PR to [gleither](https://github.com/bwireman/gleither). Implements more list-related functions than the latter."
licences = ["Apache-2.0"]
repository = { type = "github", user = "vistuleB", repo = "either_or" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
